### PR TITLE
Various updates

### PR DESCRIPTION
**Pull request by Dutchman101**
- Updated Slither library version, and made the changes compatible in script
- Fixed visual appearance of sheets page (there was no web style)
- Replaced deprecated function
- Changed default model ID for piano (for a lower chance of interference, less common vehicle)

Size reduction: 47MB > 11MB total resource size
- Optimized piano model (lower DFF and TXD file sizes) without quality impact: 3,5MB > 300kb
- Optimized sound files (re-encoded) without quality impact: 45MB > 10MB
Also counts for performance (memory & CPU load for sound device, and polycount of model for video performance)

### CODE REVIEW

**Comment by brzys** [comment]
glad to see someone interested in this resource :D
have you tested your changes?

**Comment by Dutchman101** [comment]
> have you tested your changes?
yeah, it's stable

**Comment by Dutchman101** [comment]
> glad to see someone interested in this resource :D
> have you tested your changes?

yeah, it's stable

**Comment by Dutchman101** [comment]
you don't need this patch?

**Comment by brzys** [comment]
sorry, been busy.
I've seen some inaccuracies in this patch (e.g. new parts of code that won't even execute) so I have to test it by myself.
I will merge it in few hours

**Comment by brzys** [comment]
hmm, MTA supports recursive domain requests? For me sheets were blocked.
Everything is fine now ;p

**Pull request merged**
